---
controller_execution_environments:
  - name: "EE 2.7 RHEL9 Custom"
    description: |-
      {%- raw -%}
      EE 2.7 RHEL9 Custom
      {%- endraw -%}
    organization: "Default"
    image: "quay.io/rh_ee_cparada/2.7-ee-minimal-rh-custom:latest"
    pull: "always"
    credential: "QUAY.IO Credentials"
  - name: "Hub Minimal execution environment"
    organization:  # Leave this empty organization to let the object_diff role to work properly
    image: "aap.cparada.com/ee-minimal-rhel9:2.16"
    pull: ""
  - name: "Hub Default execution environment"
    organization:  # Leave this empty organization to let the object_diff role to work properly
    image: "aap.cparada.com/ee-supported-rhel9:latest"
    pull: ""
  - name: "Minimal execution environment"
    organization:  # Leave this empty organization to let the object_diff role to work properly
    image: "registry.redhat.io/ansible-automation-platform-27/ee-minimal-rhel9:2.16"
    pull: ""
  - name: "Default execution environment"
    organization:  # Leave this empty organization to let the object_diff role to work properly
    image: "registry.redhat.io/ansible-automation-platform-27/ee-supported-rhel9:latest"
    pull: ""
  - name: "Control Plane Execution Environment"
    organization:  # Leave this empty organization to let the object_diff role to work properly
    image: "registry.redhat.io/ansible-automation-platform-27/ee-supported-rhel9:latest"
    pull: ""
...
