---
eda_decision_environments:
  - name: "Default Decision Environment"
    description: ""
    image_url: "registry.redhat.io/ansible-automation-platform-27/de-supported-rhel9:latest"
    organization: "Default"
    eda_credential: "Decision Environment Container Registry"
  - name: "Hub Default Decision Environment"
    description: ""
    image_url: "aap.cparada.com/de-supported-rhel9:latest"
    organization: "Default"
    eda_credential: "Hub Decision Environment Container Registry"
  - name: "DE 2.7 RHEL9 Custom"
    description: "DE 2.7 RHEL9 Custom"
    image_url: "quay.io/rh_ee_cparada/2.7-de-minimal-rh-custom:latest"
    organization: "Default"
    eda_credential: "QUAY.IO Credentials"
...
