---
- name: Run insights-client to report system status to Red Hat Insights
  hosts: all
  become: true

  tasks:
    - name: Run insights-client
      ansible.builtin.command:
        cmd: insights-client
      register: insights_result
      changed_when: true

    - name: Show insights-client output
      ansible.builtin.debug:
        msg: "{{ insights_result.stdout_lines }}"
